START TRANSACTION;

CREATE TABLE IF NOT EXISTS `users`(
	id VARCHAR(36) PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE,
	birthdate DATE DEFAULT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL DEFAULT NULL
);

CREATE INDEX `idx_users_id_deleted_at` ON `users` (`id`, `deleted_at`);

COMMIT;